version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tbuddy
      - POSTGRES_PASSWORD=tbuddy
      - POSTGRES_DB=tbuddy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tbuddy"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
       - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tbuddy
      - DB_USER=tbuddy
      - DB_PASS=tbuddy
      - PORT=8080
      - HOST=0.0.0.0
      - PASSWORD=password
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local
